BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    // Define Area and Authorize role.
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        // Instance of Dependency Injection
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        #region Display Company
        public IActionResult Index()
        {
            // Retrieve list of Company
            List<CompanyModel> companyList = _unitOfWork.Company.GetAll().ToList();
            return View(companyList);
        }
        #endregion

        #region Create and Edit / Upsert Company
        public IActionResult UpsertCompany(int? CompanyID)
        {
            // Check the value of CompanyID
            if( CompanyID == null || CompanyID < 0)
            {
                // Return Create View
                return View(new CompanyModel());
            }
            else
            {
                // Return Update View
                CompanyModel company = _unitOfWork.Company.Get(u=>u.CompanyID ==  CompanyID);
                return View(company);
            }            
        }

        [HttpPost]
        public IActionResult UpsertCompany(CompanyModel CompanyObj)
        {
            if (ModelState.IsValid)
            {                
                if(CompanyObj.CompanyID == 0)
                {
                    _unitOfWork.Company.Add(CompanyObj);
                    _unitOfWork.Save();
                    TempData["success"] = "Company Created Successfully";
                }
                else
                {
                    _unitOfWork.Company.Update(CompanyObj);
                    _unitOfWork.Save();
                    TempData["success"] = "Company Updated Successfully";
                }
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region Company API Call
        [HttpGet]
        public IActionResult GetAllCompanies()
        {
            // Retrieve Company List and return as JSON format.
            List<CompanyModel> companyList = _unitOfWork.Company.GetAll().ToList();
            return Json(new {data = companyList });

        }
        #endregion

        #region Company Delete
        [HttpDelete]
        public IActionResult DeleteCompany(int CompanyID)
        {
            var companyToBeDeleted = _unitOfWork.Company.Get(u => u.CompanyID == CompanyID);
            if(companyToBeDeleted == null)
            {
                return Json(new { success= false , message="Error While Deleting"});
            }
            _unitOfWork.Company.Remove(companyToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Company Deleted Successfully" });
        }
        #endregion
    }
}

BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Diagnostics;
using System.Security.Claims;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
		{
			return View();
		}

        #region Order Details
        public IActionResult OrderDetails(int orderID) 
        {
            OrderVM = new()
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(u => u.OrderHeaderID == orderID, includeProperties: "BulkyBookUser"),
                OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderID == orderID, includeProperties: "Product")
            };
            return View(OrderVM);
        }
        #endregion

        #region Update Order Detail
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.OrderHeaderID == OrderVM.OrderHeader.OrderHeaderID);
            orderHeaderFromDb.UserName = OrderVM.OrderHeader.UserName;
            orderHeaderFromDb.UserPhoneNumber = OrderVM.OrderHeader.UserPhoneNumber;   
            orderHeaderFromDb.UserStreetAddress = OrderVM.OrderHeader.UserStreetAddress;
            orderHeaderFromDb.UserCity = OrderVM.OrderHeader.UserCity;  
            orderHeaderFromDb.UserState = OrderVM.OrderHeader.UserState;    
            orderHeaderFromDb.UserPostalCode = OrderVM.OrderHeader.UserPostalCode;
            if(!string.IsNullOrEmpty(OrderVM.OrderHeader.OrderCarrier))
            {
                orderHeaderFromDb.OrderCarrier = OrderVM.OrderHeader.OrderCarrier;
            }
            if(!string.IsNullOrEmpty(OrderVM.OrderHeader.OrderTrackingNumber))
            {
                orderHeaderFromDb.OrderTrackingNumber = OrderVM.OrderHeader.OrderTrackingNumber;
            }
            _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Order Details Updated Successfully.";

            return RedirectToAction(nameof(OrderDetails),new { orderID = orderHeaderFromDb.OrderHeaderID});
        }
        #endregion

        #region Start Processing
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StartProcessing()
        {
            _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.OrderHeaderID,SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["success"] = "Order is in Processing.";
            return RedirectToAction(nameof(OrderDetails), new { orderID = OrderVM.OrderHeader.OrderHeaderID });
        }
        #endregion

        #region Ship Order
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.OrderHeaderID == OrderVM.OrderHeader.OrderHeaderID);
            orderHeader.OrderTrackingNumber = OrderVM.OrderHeader.OrderTrackingNumber;
            orderHeader.OrderCarrier = OrderVM.OrderHeader.OrderCarrier;
            orderHeader.OrderStatus = SD.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            if(orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeader.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }


            _unitOfWork.OrderHeader.Update(orderHeader);
            _unitOfWork.Save();
            TempData["success"] = "Order Shipped Successfully";
            return RedirectToAction(nameof(OrderDetails), new { orderID = OrderVM.OrderHeader.OrderHeaderID });
        }
        #endregion

        #region Cancel Order
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult CancelOrder()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.OrderHeaderID == OrderVM.OrderHeader.OrderHeaderID);

            if(orderHeader.PaymentStatus == SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentID,
                };

                var service = new RefundService();
                Refund refund = service.Create(options);
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.OrderHeaderID, SD.StatusCancelled, SD.StatusCancelled);
            }
            else
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.OrderHeaderID, SD.StatusCancelled, SD.StatusCancelled);
            }
            _unitOfWork.Save();
            TempData["success"] = "Order Cancelled Successfully";
            return RedirectToAction(nameof(OrderDetails), new { orderID = OrderVM.OrderHeader.OrderHeaderID });
        }
        #endregion

        #region Company Payment
        [HttpPost]
        [ActionName("OrderDetails")]
        public IActionResult Details_Pay_Now()
        {
            OrderVM.OrderHeader = _unitOfWork.OrderHeader.Get(u => u.OrderHeaderID == OrderVM.OrderHeader.OrderHeaderID, includeProperties: "BulkyBookUser");
            OrderVM.OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderID == OrderVM.OrderHeader.OrderHeaderID, includeProperties: "Product");

            // This is a company account with stripe logic.
            var domain = "https://localhost:7163/";
            var options = new Stripe.Checkout.SessionCreateOptions
            {
                SuccessUrl = domain + $"Admin/Order/PaymentConformation?orderHeaderID={OrderVM.OrderHeader.OrderHeaderID}",
                CancelUrl = domain + $"Admin/Order/OrderDetails?orderID={OrderVM.OrderHeader.OrderHeaderID}",
                LineItems = new List<Stripe.Checkout.SessionLineItemOptions>(),
                BillingAddressCollection = "required", // Collect the billing address
                ShippingAddressCollection = new SessionShippingAddressCollectionOptions(),
                Mode = "payment",
            };

            foreach (var item in OrderVM.OrderDetail)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.ProductPrice * 100), // Rs. 20.50 => 2050
                        Currency = "inr",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.ProductTitle
                        }
                    },
                    Quantity = item.ProductCount
                };
                options.LineItems.Add(sessionLineItem);
            }

            var service = new Stripe.Checkout.SessionService();
            Session session = service.Create(options);
            _unitOfWork.OrderHeader.UpdateStripePaymentID(OrderVM.OrderHeader.OrderHeaderID, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }
        #endregion

        #region Payment Conformation
        public IActionResult PaymentConformation(int orderHeaderID)
        {
            OrderHeaderModel orderHeaderModel = _unitOfWork.OrderHeader.Get(u => u.OrderHeaderID == orderHeaderID);
            if (orderHeaderModel.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                // This is Ordered by Company
                var service = new SessionService();
                Session session = service.Get(orderHeaderModel.PaymentSessionID);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.OrderHeader.UpdateStripePaymentID(orderHeaderID, session.Id, session.PaymentIntentId);
                    _unitOfWork.OrderHeader.UpdateStatus(orderHeaderID, orderHeaderModel.OrderStatus, SD.PaymentStatusApproved);
                    _unitOfWork.Save();
                }
            }

            return View(orderHeaderID);
        }
        #endregion

        #region Order API Call
        [HttpGet]
		public IActionResult GetAllOrders(string orderStatus)
		{
			// Retrieve product list with category names
			IEnumerable<OrderHeaderModel> orderList;

            if(User.IsInRole(SD.Role_Admin)||User.IsInRole(SD.Role_Employee))
            {
                orderList = _unitOfWork.OrderHeader.GetAll(includeProperties: "BulkyBookUser").ToList();
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var bulkyBookUserID = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                orderList = _unitOfWork.OrderHeader.GetAll(u => u.BulkyBookUserID == bulkyBookUserID, includeProperties: "BulkyBookUser");
            }


            switch (orderStatus)
            {
                case "inprocess":
                    orderList =orderList.Where(o => o.OrderStatus == SD.StatusInProcess);
                    break;
                case "pending":
                    orderList = orderList.Where(o => o.PaymentStatus == SD.PaymentStatusDelayedPayment);
                    break;
                case "completed":

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.BulkyBookUserID == claim.Value).Count());
                }
                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulky Book</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                   
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create a User</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>   
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-light">
        <div class="text-center">
            &copy;BulkyBookWeb - Made By Krutarth Zala
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.0.0/js/dataTables.min.js" ></script>
    <script src="https://cdn.tiny.cloud/1/8sf09tb1zs8ge58r3d04ww3lv3wlw4rk6h5xc71klycasxc2/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
          "positionClass": "toast-top-center"
        }
        toastr.success('@TempData["success"]')

    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-top-center"
        }
        toastr.error('@TempData["error"]')
        
    </script>
}